"""
frequency_mixer.py

Computes frequency mixing products for a
Nonlinear Hall Effect (NLHE) device.

The reported amplitudes are proportional to the
nonlinear coefficients and the excitation amplitudes,
making the spectrum physically meaningful rather than
displaying identical peaks.

Author:
Aryan Yadav
"""

from __future__ import annotations

from src.models import AnalysisResult


class FrequencyMixer:
    """
    Computes frequency mixing products generated by a
    nonlinear device excited at two frequencies.
    """

    def __init__(self, result: AnalysisResult):
        self.result = result

    # -----------------------------------------------------

    def compute(
        self,
        f1: float,
        f2: float,
        a1: float = 1.0,
        a2: float = 1.0,
    ):
        """
        Compute frequency mixing products.

        Parameters
        ----------
        f1 : float
            First excitation frequency.

        f2 : float
            Second excitation frequency.

        a1 : float, optional
            Amplitude of the first excitation current.

        a2 : float, optional
            Amplitude of the second excitation current.

        Returns
        -------
        dict
            Dictionary of mixing products.
        """

        alpha2 = abs(self.result.alpha2)
        alpha3 = abs(self.result.alpha3)

        products = {
            "f1": {
                "frequency": f1,
                "amplitude": a1,
            },
            "f2": {
                "frequency": f2,
                "amplitude": a2,
            },
            "f1 + f2": {
                "frequency": f1 + f2,
                "amplitude": alpha2 * a1 * a2,
            },
            "|f1 - f2|": {
                "frequency": abs(f1 - f2),
                "amplitude": alpha2 * a1 * a2,
            },
            "2f1": {
                "frequency": 2 * f1,
                "amplitude": alpha2 * a1**2,
            },
            "2f2": {
                "frequency": 2 * f2,
                "amplitude": alpha2 * a2**2,
            },
            "2f1 + f2": {
                "frequency": 2 * f1 + f2,
                "amplitude": alpha3 * a1**2 * a2,
            },
            "2f1 - f2": {
                "frequency": abs(2 * f1 - f2),
                "amplitude": alpha3 * a1**2 * a2,
            },
            "2f2 + f1": {
                "frequency": 2 * f2 + f1,
                "amplitude": alpha3 * a2**2 * a1,
            },
            "2f2 - f1": {
                "frequency": abs(2 * f2 - f1),
                "amplitude": alpha3 * a2**2 * a1,
            },
        }

        self.result.mixing_products = products

        return products